language: node_js
sudo: false

cache:
  directories:
    - node_modules

node_js:
  - "0.10"
script:
  - npm install
  - npm install -g gulp
  - gulp default
  - mv node_modules /tmp

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "swarmpit.io"
  skip_cleanup: true
  region: eu-central-1

after_deploy:
  - mv /tmp/node_modules .
