language: node_js
sudo: false

git:
  depth: 10
  lfs_skip_smudge: true
  
cache:
  pip: true
  directories:
    - node_modules

node_js:
  - 6
  
install:
  - npm install -ys --no-progress --depth=0
  - npm install -g gulp
  - pip install -q --upgrade pip
  - pip install -q awscli

script:
  - gulp default
  - mkdir deploy
  - rsync -av . deploy --exclude node_modules --exclude .git

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "swarmpit.io"
  skip_cleanup: true
  region: eu-central-1
  local_dir: deploy
  on:
    branch: master

after_deploy:
  - export AWS_ACCESS_KEY_ID=$AWS_CLOUDFRONT_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_CLOUDFRONT_SECRET_KEY
  - export AWS_DEFAULT_REGION=$AWS_REGION
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID --paths=/*
