language: node_js
dist: trusty
sudo: false

git:
  depth: 10
  lfs_skip_smudge: true
  
cache:
  pip: true
  directories:
    - node_modules
  
install:
  - npm install -ys --no-progress --depth=0
  - pip install -q --upgrade pip
  - pip install -q awscli

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "swarmpit.io"
  skip_cleanup: false
  region: eu-central-1
  local_dir: "s3/swarmpit.io/"
  on:
    branch: master

after_deploy:
  - export AWS_ACCESS_KEY_ID=$AWS_CLOUDFRONT_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_CLOUDFRONT_SECRET_KEY
  - export AWS_DEFAULT_REGION=$AWS_REGION
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID --paths=/*
